In [38]:
import pandas as pd
import pickle
import itertools
from ast import literal_eval

In [54]:
gdf = pickle.load(open('/home/osboxes/proj/twitter/trackIdentity/graphdf.pkl', 'rb'))
filename = '/home/osboxes/proj/twitter/tweets.data'

In [55]:
def RetrieveTweetsFromLastPoint(filename,LineMemorisied):

    # Initialisation
    maliste = []
    errors = 0
    ntweets = 0
    
    # Read New Tweets
    with open(filename) as fp:
        for line in fp:
            ntweets = ntweets + 1 
            if ntweets > LineMemorisied:
                try:
                    maliste.append(literal_eval(line))
                except:
                    errors = errors + 1

    return maliste,errors,ntweets,LineMemorisied

In [56]:
maliste,NewErrors,NewNtweets,NewLineMemorisied = RetrieveTweetsFromLastPoint(filename,0)

In [57]:
tdf = pd.DataFrame(maliste)

In [58]:
# tdf.sort_values(by="USERFNAME",ascending=False)

In [59]:
a = tdf[["USERNAME",
         "USERID",
         "USERFOLLOWERS",
         "USERFNAME",
         "USERDESCRIPTION"]].\
rename(columns = {"USERNAME" : "NAME",
                  "USERID" : "ID",
                  "USERFOLLOWERS" : "NFOL",
                  "USERFNAME" : "FNAME",
                  "USERDESCRIPTION":"DESCRIPTION"})

b = tdf[["AUTHORNAME",
         "AUTHORID",
         "AUTHORFOLLOWERS",
         "AUTHORFNAME",
         "AUTHORDESCRIPTION"]].\
rename(columns = {"AUTHORNAME" : "NAME",
                  "AUTHORID" : "ID",
                  "AUTHORFOLLOWERS" :"NFOL",
                  "AUTHORFNAME":"FNAME",
                  "AUTHORDESCRIPTION":"DESCRIPTION"})

In [60]:
tdf = pd.concat([a,b],axis=0, sort=False)
tdf.sort_values(by="FNAME",ascending=False,inplace=True)

In [62]:
tdf = tdf.drop_duplicates(subset = ["ID"])

final = gdf.\
merge(tdf,how="left",left_on="A",right_on="ID",).\
rename(columns = {"NAME" : "ANAME",
                  "NFOL":"ANFOL",
                  "DESCRIPTION" : "ADESCRIPTION","FNAME":"AFNAME"}).drop(columns='ID')

final = final.\
merge(tdf,how="left",left_on="B",right_on="ID").\
rename(columns = {"NAME" : "BNAME",
                  "NFOL":"BNFOL",
                  "DESCRIPTION" : "BDESCRIPTION","FNAME":"BFNAME"}).drop(columns=['ID'])

final.sort_values(by="f",ascending=False,inplace=True)
final = final[final.A != final.B]
final.reset_index(drop=True,inplace=True)

In [63]:
final.head()

,A,B,f,ANAME,ANFOL,AFNAME,ADESCRIPTION,BNAME,BNFOL,BFNAME,BDESCRIPTION
0,33962372,1121856729787043842,18,ChLECHEVALIER,20950,Ch.LECHEVALIER,"Gaulliste, ex-RPR / DLR, avec Marine en Ille &...",stephaneworld,270,ùë∫ùëªùë¨ùë≠ùë≠ ‚úû,"La France ‚öú, mon royaume, terre de mes anc√™tre..."
1,1121856729787043842,33962372,18,stephaneworld,270,ùë∫ùëªùë¨ùë≠ùë≠ ‚úû,"La France ‚öú, mon royaume, terre de mes anc√™tre...",ChLECHEVALIER,20950,Ch.LECHEVALIER,"Gaulliste, ex-RPR / DLR, avec Marine en Ille &..."
2,3373762791,572122341,15,GWGoldnadel,89338,G-William Goldnadel,"Avocat, essayiste, pr√©sident d'Avocats sans fr...",tprincedelamour,24364,Napol√©on,J'≈íuvre au Rassemblement des #Patriotes pour s...
3,727425382169849856,827151086733635584,15,Olivier_Monteil,12897,Olivier MONTEIL,Conseiller r√©gional RN #Occitanie I Membre du ...,dragonduclos,14759,Barbara78,Il est toujours beaucoup plus tard qu'on ne le...
4,727425382169849856,901893722857766912,15,Olivier_Monteil,12897,Olivier MONTEIL,Conseiller r√©gional RN #Occitanie I Membre du ...,Fredodu13007,663,fred üá´üá∑üá´üá∑üá∑üá∫üáÆüáπ‚úàÔ∏è,suis moi et tu verras ü§∑üèª‚Äç‚ôÇÔ∏è

In [7]:
pickle.dump(final, open('/home/osboxes/proj/twitter/trackIdentity/GraphIdentity.pkl', 'wb'))

In [8]:
print("Nombre de links :",len(final))

Nombre de links : 3218

In [9]:
print("")
print(final[["A","B","f"]].head())

<bound method NDFrame.head of                         A                    B   f
0     1121856729787043842             33962372  17
1                33962372  1121856729787043842  17
2      727425382169849856   901893722857766912  15
3      727425382169849856   827151086733635584  15
4     1121856729787043842   901893722857766912  14
...                   ...                  ...  ..
3213           2986275514           2752784274   1
3214           2986275514           2770357902   1
3215           2986275514            299730426   1
3216           2986275514             29977884   1
3217   996378340331261952           2877116435   1

[3218 rows x 3 columns]>

In [10]:
final.to_csv("graph.csv",index=False)

In [29]:
final.sort_values(by="")

,A,B,f,ANAME,ANFOL,FNAME_x,ADESCRIPTION,AUTHORFNAME_x,BNAME,BNFOL,FNAME_y,BDESCRIPTION,AUTHORFNAME_y
0,33962372,1121856729787043842,18,NaN,20950,ChLECHEVALIER,"Gaulliste, ex-RPR / DLR, avec Marine en Ille &...",Ch.LECHEVALIER,NaN,267,stephaneworld,"La France ‚öú, mon royaume, terre de mes anc√™tre...",ùë∫ùëªùë¨ùë≠ùë≠ ‚úû
1,1121856729787043842,33962372,18,NaN,267,stephaneworld,"La France ‚öú, mon royaume, terre de mes anc√™tre...",ùë∫ùëªùë¨ùë≠ùë≠ ‚úû,NaN,20950,ChLECHEVALIER,"Gaulliste, ex-RPR / DLR, avec Marine en Ille &...",Ch.LECHEVALIER
2,3373762791,572122341,15,NaN,89338,GWGoldnadel,"Avocat, essayiste, pr√©sident d'Avocats sans fr...",G-William Goldnadel,NaN,24363,tprincedelamour,J'≈íuvre au Rassemblement des #Patriotes pour s...,Napol√©on
3,727425382169849856,827151086733635584,15,NaN,12897,Olivier_Monteil,Conseiller r√©gional RN #Occitanie I Membre du ...,Olivier MONTEIL,NaN,14758,dragonduclos,Il est toujours beaucoup plus tard qu'on ne le...,Barbara78
4,727425382169849856,901893722857766912,15,NaN,12897,Olivier_Monteil,Conseiller r√©gional RN #Occitanie I Membre du ...,Olivier MONTEIL,NaN,663,Fredodu13007,suis moi et tu verras ü§∑üèª‚Äç‚ôÇÔ∏è,fred üá´üá∑üá´üá∑üá∑üá∫üáÆüáπ‚úàÔ∏è